### ISSUE TITLE
Bonus Health effect not functional.

### ISSUE THREAD

**Issue by OhLorenzo** [Auxilor/EcoArmor#12]
**Describe the bug**
The effect **Bonus Health** doesn't work properly 

**To Reproduce**
1. Give yourself any armor set that has bonus_health
2. set the health to whatever number you want, I tried tons of numbers between 10 & 250
3. Reload the plugin, and equip the armor.
4. Notice that you don't get any extra hearts.

**Expected behavior**
Well, obviously get more hearts based on what's written in the configuration

**Screenshots**
N/A

**Server Information (please complete the following information):**
- Version: **git-Purpur-1597 (MC: 1.18.2)**
- Version of plugin and eco: **Eco Version 6.29.1 EcoArmor Version 7.41.1**

**Additional context**
N/A

**Comment by ltjessem** [comment]
My understanding is that the the hearts are adjusted so max health is always displayed as 10 hearts. Check the attribute  minecraft:generic.max_health when you equip a set or:

1. Give yourself an armor set with +20 bonus health
2. Equip the armor, your health should be displayed as 5/10 hearts (because max health has doubled)
3. /heal or wait to regenerate health
4. Unequip armor , health should be displayed as 20 hearts
